"""Cria a base do banco de dados

Revision ID: 8b4348ca16a1
Revises: 
Create Date: 2025-09-09 18:55:19.119060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4348ca16a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_de_atuacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('predio', sa.String(length=50), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina_areas',
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas_de_atuacao.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('disciplina_id', 'area_id')
    )
    op.create_table('disponibilidade_professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocupacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_areas',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas_de_atuacao.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'area_id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('periodo', sa.Enum('Matutino', 'Vespertino', 'Noturno'), nullable=True),
    sa.Column('num_alunos', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    op.drop_table('professor_areas')
    op.drop_table('ocupacoes')
    op.drop_table('disponibilidades')
    op.drop_table('disponibilidade_professores')
    op.drop_table('disciplina_areas')
    op.drop_table('salas')
    op.drop_table('professores')
    op.drop_table('disciplinas')
    op.drop_table('areas_de_atuacao')
    # ### end Alembic commands ###
